version: "3"
services:
  # neo4j:
  #   image: neo4j:4.0.3
  #   container_name: neo4j-db
  #   restart: unless-stopped
  #   ports:
  #     - 7474:7474
  #     - 7687:7687
  #   volumes:
  #     - ./neo4j/conf:/conf
  #     - ./neo4j/data:/data
  #     - ./neo4j/import:/import
  #     - ./neo4j/logs:/logs
  #     - ./neo4j/plugins:/plugins
  #   environment:
  #     # Raise memory limits
  #     - NEO4J_dbms_memory_pagecache_size=1G
  #     - NEO4J_dbms.memory.heap.initial_size=1G
  #     - NEO4J_dbms_memory_heap_max__size=1G
  db:
    image: mysql:8
    container_name: mysql-db
    restart: unless-stopped
    ports:
      - 15000:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: your_password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
  # Hive配置:
  # namenode:
  #   image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
  #   volumes:
  #     - ./hive/namenode:/hadoop/dfs/name
  #   environment:
  #     - CLUSTER_NAME=test
  #   env_file:
  #     - ./hive/hadoop-hive.env
  #   ports:
  #     - "50070:50070"
  # datanode:
  #   image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
  #   volumes:
  #     - ./hive/datanode:/hadoop/dfs/data
  #   env_file:
  #     - ./hive/hadoop-hive.env
  #   environment:
  #     SERVICE_PRECONDITION: "namenode:50070"
  #   ports:
  #     - "50075:50075"
  # hive-server:
  #   image: bde2020/hive:2.3.2-postgresql-metastore
  #   env_file:
  #     - ./hive/hadoop-hive.env
  #   environment:
  #     HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
  #     SERVICE_PRECONDITION: "hive-metastore:9083"
  #   ports:
  #     - "10000:10000"
  # hive-metastore:
  #   image: bde2020/hive:2.3.2-postgresql-metastore
  #   env_file:
  #     - ./hive/hadoop-hive.env
  #   command: /opt/hive/bin/hive --service metastore
  #   environment:
  #     SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
  #   ports:
  #     - "9083:9083"
  # hive-metastore-postgresql:
  #   image: bde2020/hive-metastore-postgresql:2.3.0
  # presto-coordinator:
  #   image: shawnzhu/prestodb:0.181
  #   ports:
  #     - "8080:8080"
